### ISSUE TITLE
Cannot compile on linux with Pawn 3.10.10 compiler

### ISSUE THREAD

**Issue by Papawy** [pawn-lang/YSI-Includes#565]
Hello,

I am currently developing with `sampctl` on WSL2 (Ubuntu 20.04).

In my `pawn.yaml` I have:
```yaml
dependencies:
- sampctl/samp-stdlib
- pawn-lang/YSI-Includes@5.x
builds:
- name: dev
  args:
  - -Z+
  - -v2
```

I am trying to build with:
`sampctl package build --verbose --forceEnsure`

My script:
```pawn
#include "gamemode\gamemode.pwn"

main()
{
	print("Launching gamemode"\r\n");
	return 1;
}
```
```pawn
// gamemode.pwn
#include <YSI_Coding\y_hooks>

//#include "constants.pwn"
//#include "utils.pwn"
```

It seems to compile indefinitely with the compiler thread at 100% of load (I let it for 20min, and even if it was compiling in 20 minutes it would be a bit too long..). `sampctl` is just showing the line executing the compiler and then nothing, it is hanging there.

So it's basically just including `y_hooks` and nothing else. If I comment the `YSI` inclusion then it is compiling.

Is there something I am doing wrong? I did not saw similar issue right here. Thanks!
